---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pobdesig/repositories/portofolio
    - /bin/cp src/index.html $DEPLOYPATH
    - /bin/cp src/styles.css $DEPLOYPATH
    - /bin/cp -R /src/assets $DEPLOYPATH
